version: 2
builds:
  - goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: darwin
        goarch: '386'
    env:
      - CGO_ENABLED=0
archives:
  - id: tar.gz
    formats: ['tar.gz']
    format_overrides:
      - goos: windows
        formats: ['zip']
  - id: binary
    formats: ['binary']
